#!/usr/bin/env bash
# Run the Android side of the equivalence test suite.
#
# Usage:
#   ./scripts/run_android.sh                # run all (hand-crafted + generated)
#   ./scripts/run_android.sh --no-generated # run only hand-crafted scenarios
#
# Prerequisites:
#   - JDK 21+ installed (with javac)
#   - Android SDK configured
#   - gradlew available
#
# This script must be run from the Android repo root:
#   cd /path/to/elimtiyaz-android
#   bash financial-tests/equivalence/scripts/run_android.sh
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(dirname "$SCRIPT_DIR")"
ANDROID_REPO_ROOT="$(cd "$ROOT_DIR/../.." && pwd)"
cd "$ANDROID_REPO_ROOT"

INCLUDE_GENERATED=true
if [[ "${1:-}" == "--no-generated" ]]; then
  INCLUDE_GENERATED=false
fi

# Ensure the generated scenarios exist (copy from desktop repo if missing).
# Both repos share the same equivalence/ directory contents.
if $INCLUDE_GENERATED && [[ ! -d "$ROOT_DIR/generated" || -z "$(ls -A "$ROOT_DIR/generated" 2>/dev/null)" ]]; then
  echo "─── Generating scenarios via Node (deterministic seed) ───"
  # If tsx is available in this repo, use it; otherwise copy from desktop.
  if command -v npx >/dev/null 2>&1 && [[ -f "$ROOT_DIR/generators/scenario_generator.ts" ]]; then
    DESKTOP_REPO="$(cd "$ROOT_DIR/../../../AgentGithubUplaod/elimtiyaz-desktop" 2>/dev/null || echo "")"
    if [[ -n "$DESKTOP_REPO" && -d "$DESKTOP_REPO/node_modules" ]]; then
      (cd "$DESKTOP_REPO" && npx tsx "$ROOT_DIR/generators/scenario_generator.ts" --count=500 --seed=42)
    else
      echo "ERROR: Cannot generate scenarios — tsx not available and desktop repo not found."
      echo "Run the generator from the desktop repo first:"
      echo "  cd AgentGithubUplaod/elimtiyaz-desktop"
      echo "  npx tsx financial-tests/equivalence/generators/scenario_generator.ts --count=500 --seed=42"
      echo "Then copy generated/*.json to this repo's financial-tests/equivalence/generated/."
      exit 1
    fi
  fi
fi

# Run the Android runner as a JUnit test.
echo "─── Running Android engine ───"
SCENARIOS_DIR="$ROOT_DIR/scenarios"
if $INCLUDE_GENERATED && [[ -d "$ROOT_DIR/generated" ]]; then
  # Concatenate hand-crafted + generated by running twice (or use a combined dir).
  # For simplicity, run scenarios/ first, then generated/.
  ./gradlew :app:testDebugUnitTest --tests '*AndroidEquivalenceRunner*' \
    -PandroidEquivalence.scenariosDir="$SCENARIOS_DIR" \
    -PandroidEquivalence.outputDir="$ROOT_DIR/results/android" || true

  ./gradlew :app:testDebugUnitTest --tests '*AndroidEquivalenceRunner*' \
    -PandroidEquivalence.scenariosDir="$ROOT_DIR/generated" \
    -PandroidEquivalence.outputDir="$ROOT_DIR/results/android" || true
else
  ./gradlew :app:testDebugUnitTest --tests '*AndroidEquivalenceRunner*' \
    -PandroidEquivalence.scenariosDir="$SCENARIOS_DIR" \
    -PandroidEquivalence.outputDir="$ROOT_DIR/results/android" || true
fi

echo ""
echo "─── Android side complete ───"
echo "Results: $ROOT_DIR/results/android/"
