package com.example.equivalence

import kotlinx.serialization.json.Json
import kotlinx.serialization.json.JsonArray
import kotlinx.serialization.json.jsonObject
import kotlinx.serialization.json.jsonPrimitive
import kotlinx.serialization.json.JsonElement
import kotlinx.serialization.json.JsonNull
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.JsonPrimitive
import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Test
import java.io.File

/**
 * CrossPlatformEquivalenceTest — PARITY-003 / T-292 (45th session,
 * 2026-09-11). The owner's 13-chart parity mandate made this suite
 * explicit: "Create an end-to-end mathematical and visual equivalence
 * test suite (CrossPlatformEquivalenceTest.kt): load a shared reference
 * dataset … compute all 13 visualizations and statistical summaries
 * using the TypeScript engines and the Kotlin engines; assert that all
 * derived numbers, bins, percentages, and status tags are identical
 * across both platforms."
 *
 * How the cross-platform proof works here (the SAME corpus discipline as
 * AndroidEquivalenceTest / the T-285 suite, extended to the visual
 * derivations):
 *
 *  1. The HUB repo carries the canonical `analytics_visuals` scenarios
 *     (financial-tests/equivalence/scenarios/analytics_visuals_*.json).
 *     Their `then` blocks were generated by running the REAL DESKTOP TS
 *     derivations (scripts/generate_analytics_visuals_corpus.ts — the
 *     analytics_bridge over analytics-derivations.ts, the component
 *     extractions, and the repository demographics body).
 *  2. THIS test loads each scenario, runs the ANDROID engine
 *     (core/StatisticsEngine — the ADR-002 mirror) over the same `given`
 *     through the same op the AndroidEquivalenceRunner implements, and
 *     asserts the result equals the desktop-generated `then` on EVERY
 *     value: bins, levels, percentages, cumulative curves, deltas (incl.
 *     the null "n/a" semantics), wave health + next-target flags, and
 *     every demographics slice.
 *  3. The desktop-vs-android full-corpus comparison (triple comparator)
 *     additionally re-proves equivalence on the runner outputs.
 *
 * A failure here means the Android engine would render a DIFFERENT
 * number than the desktop for the same data — the exact defect class
 * the mandate targets.
 */
class CrossPlatformEquivalenceTest {

    private val json = Json { ignoreUnknownKeys = true }

    @Test
    fun `every analytics_visuals scenario matches the desktop-generated expectations`() {
        val scenariosDir = resolveScenariosDir()
        val files = scenariosDir.listFiles { f -> f.name.startsWith("analytics_visuals") && f.name.endsWith(".json") }
        assertTrue(
            "No analytics_visuals scenarios found in ${scenariosDir.absolutePath} — the hub repo must be checked out as a sibling (see AndroidEquivalenceTest path resolution).",
            files != null && files.isNotEmpty(),
        )

        var checked = 0
        files!!.sortedBy { it.name }.forEach { file ->
            val scenario = json.parseToJsonElement(file.readText()).jsonObject
            val id = scenario["id"]!!.jsonPrimitive.content
            val thenBlock = scenario["then"] as? JsonObject
            assertTrue("Scenario $id has no then block — run scripts/generate_analytics_visuals_corpus.ts in the hub", thenBlock != null && thenBlock.isNotEmpty())

            val result = AndroidEquivalenceRunner.runScenarioForTest(file.readText())
            assertTrue(
                "Scenario $id errored: ${result?.get("error")}",
                result != null && result["error"] == null,
            )

            assertDeepEquals("$id weeklyRhythm", thenBlock!!["weeklyRhythm"]!!, result!!["weeklyRhythm"]!!)
            assertDeepEquals("$id heatmap", thenBlock["heatmap"]!!, result["heatmap"]!!)
            assertDeepEquals("$id yoy", thenBlock["yoy"]!!, result["yoy"]!!)
            assertDeepEquals("$id trancheWaves", thenBlock["trancheWaves"]!!, result["trancheWaves"]!!)
            assertDeepEquals("$id demographics", thenBlock["demographics"]!!, result["demographics"]!!)
            checked++
        }
        println("CrossPlatformEquivalenceTest: $checked scenario(s) × 5 derivation families — all identical to the desktop TS engine output.")
    }

    // ── Deep structural equality with precise failure messages ─────────────

    private fun assertDeepEquals(path: String, expected: JsonElement, actual: JsonElement) {
        when {
            expected is JsonObject && actual is JsonObject -> {
                assertEquals("$path: key sets differ (desktop=${expected.keys.sorted()}, android=${actual.keys.sorted()})", expected.keys, actual.keys)
                expected.keys.forEach { k ->
                    assertDeepEquals("$path.$k", expected[k]!!, actual[k]!!)
                }
            }
            expected is JsonArray && actual is JsonArray -> {
                assertEquals("$path: array lengths differ (desktop=${expected.size}, android=${actual.size})", expected.size, actual.size)
                expected.forEachIndexed { i, e ->
                    assertDeepEquals("$path[$i]", e, actual[i])
                }
            }
            expected is JsonPrimitive && actual is JsonPrimitive -> {
                assertEquals("$path: values differ (desktop=${expected.content}, android=${actual.content})", expected.content, actual.content)
            }
            expected is JsonNull && actual is JsonNull -> { /* both null — equal */ }
            else -> assertEquals("$path: JSON kinds differ (desktop=$expected, android=$actual)", expected, actual)
        }
    }

    // ── Path resolution (the AndroidEquivalenceTest probe list) ─────────────

    private fun resolveScenariosDir(): File {
        val relative = "financial-tests/equivalence/scenarios"
        val cwd = File(System.getProperty("user.dir") ?: ".")
        File(cwd, relative).takeIf { it.isDirectory }?.let { return it }
        File(cwd.parentFile ?: cwd, relative).takeIf { it.isDirectory }?.let { return it }
        val reposDir = cwd.parentFile?.parentFile ?: cwd
        File(reposDir, "AgentGithubUplaod/elimtiyaz-desktop/$relative").takeIf { it.isDirectory }?.let { return it }
        File(reposDir, "elimtiyaz-desktop/$relative").takeIf { it.isDirectory }?.let { return it }
        return File(cwd, relative)
    }
}
