package com.example.equivalence

import kotlinx.serialization.json.Json
import kotlinx.serialization.json.JsonArray
import kotlinx.serialization.json.jsonObject
import kotlinx.serialization.json.jsonPrimitive
import kotlinx.serialization.json.long
import kotlinx.serialization.json.JsonElement
import kotlinx.serialization.json.JsonNull
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.JsonPrimitive
import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Test
import java.io.File

/**
 * CrossPlatformEquivalenceTest — PARITY-003 / T-292 (45th session,
 * 2026-09-11). The owner's 13-chart parity mandate made this suite
 * explicit: "Create an end-to-end mathematical and visual equivalence
 * test suite (CrossPlatformEquivalenceTest.kt): load a shared reference
 * dataset … compute all 13 visualizations and statistical summaries
 * using the TypeScript engines and the Kotlin engines; assert that all
 * derived numbers, bins, percentages, and status tags are identical
 * across both platforms."
 *
 * How the cross-platform proof works here (the SAME corpus discipline as
 * AndroidEquivalenceTest / the T-285 suite, extended to the visual
 * derivations):
 *
 *  1. The HUB repo carries the canonical `analytics_visuals` scenarios
 *     (financial-tests/equivalence/scenarios/analytics_visuals_*.json).
 *     Their `then` blocks were generated by running the REAL DESKTOP TS
 *     derivations (scripts/generate_analytics_visuals_corpus.ts — the
 *     analytics_bridge over analytics-derivations.ts, the component
 *     extractions, and the repository demographics body).
 *  2. THIS test loads each scenario, runs the ANDROID engine
 *     (core/StatisticsEngine — the ADR-002 mirror) over the same `given`
 *     through the same op the AndroidEquivalenceRunner implements, and
 *     asserts the result equals the desktop-generated `then` on EVERY
 *     value: bins, levels, percentages, cumulative curves, deltas (incl.
 *     the null "n/a" semantics), wave health + next-target flags, and
 *     every demographics slice.
 *  3. The desktop-vs-android full-corpus comparison (triple comparator)
 *     additionally re-proves equivalence on the runner outputs.
 *
 * A failure here means the Android engine would render a DIFFERENT
 * number than the desktop for the same data — the exact defect class
 * the mandate targets.
 */
class CrossPlatformEquivalenceTest {

    private val json = Json { ignoreUnknownKeys = true }

    @Test
    fun `every analytics_visuals scenario matches the desktop-generated expectations`() {
        val scenariosDir = resolveScenariosDir()
        val files = scenariosDir.listFiles { f -> f.name.startsWith("analytics_visuals") && f.name.endsWith(".json") }
        assertTrue(
            "No analytics_visuals scenarios found in ${scenariosDir.absolutePath} — the hub repo must be checked out as a sibling (see AndroidEquivalenceTest path resolution).",
            files != null && files.isNotEmpty(),
        )

        var checked = 0
        files!!.sortedBy { it.name }.forEach { file ->
            val scenario = json.parseToJsonElement(file.readText()).jsonObject
            val id = scenario["id"]!!.jsonPrimitive.content
            val thenBlock = scenario["then"] as? JsonObject
            assertTrue("Scenario $id has no then block — run scripts/generate_analytics_visuals_corpus.ts in the hub", thenBlock != null && thenBlock.isNotEmpty())

            val result = AndroidEquivalenceRunner.runScenarioForTest(file.readText())
            assertTrue(
                "Scenario $id errored: ${result?.get("error")}",
                result != null && result["error"] == null,
            )

            assertDeepEquals("$id weeklyRhythm", thenBlock!!["weeklyRhythm"]!!, result!!["weeklyRhythm"]!!)
            // T-341 (STATS-400): the heatmap assertion REMOVED with the vanity
            // statistic (owner kill list — the regenerated corpus has no
            // heatmap key; the runner no longer computes it).
            assertDeepEquals("$id yoy", thenBlock["yoy"]!!, result["yoy"]!!)
            assertDeepEquals("$id trancheWaves", thenBlock["trancheWaves"]!!, result["trancheWaves"]!!)
            assertDeepEquals("$id demographics", thenBlock["demographics"]!!, result["demographics"]!!)
            checked++
        }
        println("CrossPlatformEquivalenceTest: $checked scenario(s) × 4 derivation families — all identical to the desktop TS engine output.")
    }

    /**
     * T-341 (STATS-400, 61st session) — the EXECUTIVE-STATISTICS corpus:
     * every executive_statistics scenario's desktop-generated `then` block
     * must equal the Android core/ExecutiveStatistics.kt output on EVERY
     * value — waves, erosion, triage (+ call list), concentration,
     * transport, services, dynamics (+ section imbalance), riskSummary.
     * This is the owner's ONE-calculation-source mandate made executable.
     */
    @Test
    fun `every executive_statistics scenario matches the desktop-generated expectations`() {
        val scenariosDir = resolveScenariosDir()
        val files = scenariosDir.listFiles { f -> f.name.startsWith("executive_statistics") && f.name.endsWith(".json") }
        assertTrue(
            "No executive_statistics scenarios found in ${scenariosDir.absolutePath} — the hub repo must be checked out as a sibling (see AndroidEquivalenceTest path resolution).",
            files != null && files.isNotEmpty(),
        )

        var checked = 0
        files!!.sortedBy { it.name }.forEach { file ->
            val scenario = json.parseToJsonElement(file.readText()).jsonObject
            val id = scenario["id"]!!.jsonPrimitive.content
            val thenBlock = scenario["then"] as? JsonObject
            assertTrue("Scenario $id has no then block — run scripts/generate_executive_statistics_corpus.ts in the hub", thenBlock != null && thenBlock.isNotEmpty())

            val result = AndroidEquivalenceRunner.runScenarioForTest(file.readText())
            assertTrue(
                "Scenario $id errored: ${result?.get("error")}",
                result != null && result["error"] == null,
            )

            for (key in thenBlock!!.keys) {
                assertDeepEquals("$id $key", thenBlock[key]!!, result!![key]!!)
            }
            checked++
        }
        println("CrossPlatformEquivalenceTest: $checked executive_statistics scenario(s) × 8 derivation families — all identical to the desktop TS engine output.")
    }

    /**
     * T-455 (PARITY-007, 127th session) — the UI-SURFACE corpus: the
     * dedicated cross-platform parity test for the DISPLAY layer. The owner's
     * issue-#1 mandate (§6/§11: the full data-flow comparison must reach the
     * UI-facing values; the underlying values must actually match, never
     * merely be formatted similarly) made this suite explicit:
     *
     *  1. The hub corpus carries the `deriveUiSurfaces` scenario(s) whose
     *     `then` blocks were generated by running the REAL DESKTOP
     *     derivations (the analytics_bridge strip adapters over the canonical
     *     `derivePooledTrancheWaves`) — the given mixes the REAL Excel
     *     2025-2026 corpus family (t105_00267128 — the source-of-truth
     *     totals 23 850 000 DZD charged = paid) with the LIVE 2026-2027
     *     shape (the FI registration fee at tranche 0, the V1-label price
     *     ladder, the transport T1, the uncleared cheque, the future waves).
     *  2. THIS test loads each scenario, runs the ANDROID engine (the same
     *     canonical Kotlin derivations the production screens consume —
     *     deriveExecTrancheWaveStrip / deriveExecTrancheStripTotals /
     *     deriveExecPooledTrancheWaves / deriveExecNonWaveSummary) over the
     *     same `given`, and asserts the result equals the desktop-generated
     *     `then` on EVERY value: the Finance-strip wave view models (pooled
     *     basis, canonical unclamped rate, derived due-date range, isOverdue,
     *     INV-4 remaining, tuition-isolated rate), the 4-cell strip totals,
     *     the wave-velocity card slots (the T-427 status flags, the T-434
     *     days-late, the T-447 global badges), and the non-wave « Hors
     *     Tranches » groups.
     *  3. The Excel source-of-truth leg: the strip totals must equal the
     *     scenario's own Excel-derived sums (the t105 family's 23 850 000
     *     DZD charged/paid is INSIDE the totals), and every pooled wave must
     *     hold the T-447 reconciliation identity
     *     `dueTotal + overCoverageTotal = paidTotal + pendingTotal + remainingTotal`
     *     — the mandate's "Total Due = Paid + Pending + Remaining" verified
     *     numerically, never via formatted strings.
     */
    @Test
    fun `every ui_surfaces scenario matches the desktop-generated expectations`() {
        val scenariosDir = resolveScenariosDir()
        val files = scenariosDir.listFiles { f -> f.name.startsWith("executive_statistics") && f.name.endsWith(".json") }
        assertTrue(
            "No executive_statistics scenarios found in ${scenariosDir.absolutePath} — the hub repo must be checked out as a sibling (see AndroidEquivalenceTest path resolution).",
            files != null && files.isNotEmpty(),
        )

        var checked = 0
        var identitiesChecked = 0
        files!!.sortedBy { it.name }.forEach { file ->
            val scenario = json.parseToJsonElement(file.readText()).jsonObject
            val whenBlock = scenario["when"] as? JsonObject
            val opType = whenBlock?.get("type")?.jsonPrimitive?.content
            if (opType != "deriveUiSurfaces") return@forEach
            val id = scenario["id"]!!.jsonPrimitive.content
            val thenBlock = scenario["then"] as? JsonObject
            assertTrue("Scenario $id has no then block — run scripts/generate_executive_statistics_corpus.ts in the hub", thenBlock != null && thenBlock.isNotEmpty())

            val result = AndroidEquivalenceRunner.runScenarioForTest(file.readText())
            assertTrue(
                "Scenario $id errored: ${result?.get("error")}",
                result != null && result["error"] == null,
            )

            for (key in thenBlock!!.keys) {
                assertDeepEquals("$id $key", thenBlock[key]!!, result!![key]!!)
            }

            // ── The T-447 reconciliation identity (the mandate's Total Due =
            // Paid + Pending + Remaining) — asserted NUMERICALLY on every
            // wave card slot AND the global pool (the corpus fields pin the
            // legs; this proves the identity, not a formatted string).
            val slots = (thenBlock["waveVelocityCards"] as JsonObject)["slots"] as kotlinx.serialization.json.JsonArray
            slots.forEach { slotEl ->
                val slot = slotEl.jsonObject
                val due = slot["dueTotal"]!!.jsonPrimitive.long
                val paid = slot["paidTotal"]!!.jsonPrimitive.long
                val pending = slot["pendingTotal"]!!.jsonPrimitive.long
                val remaining = slot["remainingTotal"]!!.jsonPrimitive.long
                val overCoverage = slot["overCoverageTotal"]!!.jsonPrimitive.long
                assertEquals(
                    "$id wave ${slot["wave"]}: the reconciliation identity dueTotal + overCoverageTotal = paidTotal + pendingTotal + remainingTotal is broken",
                    paid + pending + remaining,
                    due + overCoverage,
                )
                identitiesChecked++
            }

            // ── The Excel source-of-truth leg: the strip totals are the
            // canonical sums over the WHOLE selection (the Excel family's
            // 23 850 000 DZD charged + the live-shape rows — computed here
            // from the scenario's own given, the source-of-truth rows).
            val given = scenario["given"] as JsonObject
            val installments = given["installments"] as kotlinx.serialization.json.JsonArray
            var excelDue = 0L
            var excelPaid = 0L
            var excelPending = 0L
            installments.forEach { el ->
                val i = el.jsonObject
                excelDue += i["amountDue"]!!.jsonPrimitive.long
                excelPaid += (i["amountPaid"]?.jsonPrimitive?.long ?: 0L)
                excelPending += (i["amountPending"]?.jsonPrimitive?.long ?: 0L)
            }
            val totals = thenBlock["financeStripTotals"]!!.jsonObject
            assertEquals("$id strip totals: totalDue ≠ the Σ amountDue over the source-of-truth rows", excelDue, totals["totalDue"]!!.jsonPrimitive.long)
            assertEquals("$id strip totals: totalPaid ≠ the Σ amountPaid over the source-of-truth rows", excelPaid, totals["totalPaid"]!!.jsonPrimitive.long)
            assertEquals("$id strip totals: totalRemaining ≠ clamp(Σdue − Σpaid − Σpending)", (excelDue - excelPaid - excelPending).coerceAtLeast(0L), totals["totalRemaining"]!!.jsonPrimitive.long)
            checked++
        }
        println("CrossPlatformEquivalenceTest: $checked ui_surfaces scenario(s) — the wave cards + the Finance strip + the strip totals + $identitiesChecked reconciliation identities all identical to the desktop TS engine output and the Excel source-of-truth sums.")
    }

    // ── Deep structural equality with precise failure messages ─────────────

    private fun assertDeepEquals(path: String, expected: JsonElement, actual: JsonElement) {
        when {
            expected is JsonObject && actual is JsonObject -> {
                assertEquals("$path: key sets differ (desktop=${expected.keys.sorted()}, android=${actual.keys.sorted()})", expected.keys, actual.keys)
                expected.keys.forEach { k ->
                    assertDeepEquals("$path.$k", expected[k]!!, actual[k]!!)
                }
            }
            expected is JsonArray && actual is JsonArray -> {
                assertEquals("$path: array lengths differ (desktop=${expected.size}, android=${actual.size})", expected.size, actual.size)
                expected.forEachIndexed { i, e ->
                    assertDeepEquals("$path[$i]", e, actual[i])
                }
            }
            expected is JsonPrimitive && actual is JsonPrimitive -> {
                assertEquals("$path: values differ (desktop=${expected.content}, android=${actual.content})", expected.content, actual.content)
            }
            expected is JsonNull && actual is JsonNull -> { /* both null — equal */ }
            else -> assertEquals("$path: JSON kinds differ (desktop=$expected, android=$actual)", expected, actual)
        }
    }

    // ── Path resolution (the AndroidEquivalenceTest probe list) ─────────────

    private fun resolveScenariosDir(): File {
        val relative = "financial-tests/equivalence/scenarios"
        val cwd = File(System.getProperty("user.dir") ?: ".")
        File(cwd, relative).takeIf { it.isDirectory }?.let { return it }
        File(cwd.parentFile ?: cwd, relative).takeIf { it.isDirectory }?.let { return it }
        val reposDir = cwd.parentFile?.parentFile ?: cwd
        File(reposDir, "AgentGithubUplaod/elimtiyaz-desktop/$relative").takeIf { it.isDirectory }?.let { return it }
        File(reposDir, "elimtiyaz-desktop/$relative").takeIf { it.isDirectory }?.let { return it }
        return File(cwd, relative)
    }
}
