-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.tenants (
  id uuid NOT NULL DEFAULT gen_uuid(),
  slug text NOT NULL UNIQUE,
  name text NOT NULL,
  legal_name text,
  tax_id text,
  address text,
  city text,
  postal_code text,
  country text NOT NULL DEFAULT 'DZ'::text,
  phone text,
  email text,
  website text,
  logo_path text,
  default_locale text NOT NULL DEFAULT 'fr'::text,
  default_currency text NOT NULL DEFAULT 'DZD'::text,
  timezone text NOT NULL DEFAULT 'Africa/Algiers'::text,
  is_active boolean NOT NULL DEFAULT true,
  settings jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  deleted_at timestamp with time zone,
  CONSTRAINT tenants_pkey PRIMARY KEY (id)
);
CREATE TABLE public.user_profiles (
  id uuid NOT NULL DEFAULT gen_uuid(),
  auth_user_id uuid NOT NULL UNIQUE,
  tenant_id uuid,
  email text NOT NULL,
  display_name text,
  avatar_url text,
  phone text,
  locale text NOT NULL DEFAULT 'fr'::text,
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'active'::text, 'suspended'::text, 'deleted'::text])),
  approval_request_id uuid,
  last_login_at timestamp with time zone,
  last_login_ip inet,
  last_user_agent text,
  password_changed_at timestamp with time zone,
  failed_login_count integer NOT NULL DEFAULT 0,
  locked_until timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT user_profiles_pkey PRIMARY KEY (id),
  CONSTRAINT user_profiles_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id)
);
CREATE TABLE public.account_approval_requests (
  id uuid NOT NULL DEFAULT gen_uuid(),
  tenant_id uuid,
  auth_user_id uuid NOT NULL UNIQUE,
  email text NOT NULL,
  requested_role text NOT NULL DEFAULT 'parent'::text CHECK (requested_role = ANY (ARRAY['parent'::text, 'student'::text, 'staff'::text])),
  requested_at timestamp with time zone NOT NULL DEFAULT now(),
  activation_code text,
  national_id text,
  phone text,
  full_name text,
  notes_from_user text,
  target_parent_id uuid,
  target_student_id uuid,
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'approved'::text, 'rejected'::text, 'expired'::text])),
  reviewed_by uuid,
  reviewed_at timestamp with time zone,
  decision_note text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  expires_at timestamp with time zone NOT NULL DEFAULT (now() + '7 days'::interval),
  CONSTRAINT account_approval_requests_pkey PRIMARY KEY (id),
  CONSTRAINT account_approval_requests_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id)
);
CREATE TABLE public.sessions (
  id uuid NOT NULL DEFAULT gen_uuid(),
  user_profile_id uuid NOT NULL,
  tenant_id uuid,
  supabase_session_id text,
  refresh_token_jti text,
  ip_address inet,
  user_agent text,
  device_name text,
  started_at timestamp with time zone NOT NULL DEFAULT now(),
  last_activity_at timestamp with time zone NOT NULL DEFAULT now(),
  expires_at timestamp with time zone NOT NULL,
  revoked_at timestamp with time zone,
  revoked_reason text,
  CONSTRAINT sessions_pkey PRIMARY KEY (id),
  CONSTRAINT sessions_user_profile_id_fkey FOREIGN KEY (user_profile_id) REFERENCES public.user_profiles(id),
  CONSTRAINT sessions_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id)
);
CREATE TABLE public.roles (
  id uuid NOT NULL DEFAULT gen_uuid(),
  code text NOT NULL UNIQUE,
  label_fr text NOT NULL,
  label_ar text,
  label_en text,
  description text,
  staff_category text CHECK (staff_category = ANY (ARRAY['administration'::text, 'teaching'::text, 'support'::text, 'medical'::text, NULL::text])),
  is_staff_role boolean NOT NULL DEFAULT false,
  is_web_role boolean NOT NULL DEFAULT false,
  sort_order integer NOT NULL DEFAULT 100,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT roles_pkey PRIMARY KEY (id)
);
CREATE TABLE public.permissions (
  id uuid NOT NULL DEFAULT gen_uuid(),
  code text NOT NULL UNIQUE,
  label_fr text NOT NULL,
  label_ar text,
  label_en text,
  domain text NOT NULL CHECK (domain = ANY (ARRAY['crm'::text, 'academic'::text, 'financial'::text, 'expense'::text, 'hr'::text, 'workflow'::text, 'routing'::text, 'settings'::text, 'backup'::text, 'ai'::text, 'operations'::text, 'workforce'::text, 'audit'::text, 'notification'::text, 'calendar'::text])),
  description text,
  sort_order integer NOT NULL DEFAULT 100,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT permissions_pkey PRIMARY KEY (id)
);
CREATE TABLE public.role_permissions (
  role_id uuid NOT NULL,
  permission_id uuid NOT NULL,
  CONSTRAINT role_permissions_pkey PRIMARY KEY (role_id, permission_id),
  CONSTRAINT role_permissions_role_id_fkey FOREIGN KEY (role_id) REFERENCES public.roles(id),
  CONSTRAINT role_permissions_permission_id_fkey FOREIGN KEY (permission_id) REFERENCES public.permissions(id)
);
CREATE TABLE public.tenant_role_overrides (
  id uuid NOT NULL DEFAULT gen_uuid(),
  tenant_id uuid NOT NULL,
  role_id uuid NOT NULL,
  permission_id uuid NOT NULL,
  action text NOT NULL CHECK (action = ANY (ARRAY['grant'::text, 'deny'::text])),
  created_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT tenant_role_overrides_pkey PRIMARY KEY (id),
  CONSTRAINT tenant_role_overrides_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id),
  CONSTRAINT tenant_role_overrides_role_id_fkey FOREIGN KEY (role_id) REFERENCES public.roles(id),
  CONSTRAINT tenant_role_overrides_permission_id_fkey FOREIGN KEY (permission_id) REFERENCES public.permissions(id)
);
CREATE TABLE public.role_assignments (
  id uuid NOT NULL DEFAULT gen_uuid(),
  user_profile_id uuid NOT NULL,
  tenant_id uuid NOT NULL,
  role_id uuid NOT NULL,
  assigned_by uuid,
  assigned_at timestamp with time zone NOT NULL DEFAULT now(),
  revoked_at timestamp with time zone,
  CONSTRAINT role_assignments_pkey PRIMARY KEY (id),
  CONSTRAINT role_assignments_user_profile_id_fkey FOREIGN KEY (user_profile_id) REFERENCES public.user_profiles(id),
  CONSTRAINT role_assignments_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id),
  CONSTRAINT role_assignments_role_id_fkey FOREIGN KEY (role_id) REFERENCES public.roles(id)
);
CREATE TABLE public.academic_years (
  id uuid NOT NULL DEFAULT gen_uuid(),
  tenant_id uuid NOT NULL,
  label text NOT NULL,
  start_date date NOT NULL,
  end_date date NOT NULL,
  term_structure text NOT NULL CHECK (term_structure = ANY (ARRAY['semester'::text, 'trimester'::text, 'quarter'::text])),
  is_current boolean NOT NULL DEFAULT false,
  is_archived boolean NOT NULL DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  code text,
  CONSTRAINT academic_years_pkey PRIMARY KEY (id),
  CONSTRAINT academic_years_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id)
);
CREATE TABLE public.academic_levels (
  id uuid NOT NULL DEFAULT gen_uuid(),
  tenant_id uuid NOT NULL,
  cycle text NOT NULL CHECK (cycle = ANY (ARRAY['primaire'::text, 'cem'::text, 'lycee'::text, 'prescolaire'::text])),
  year_label text NOT NULL,
  year_number integer NOT NULL,
  grade_code text NOT NULL,
  sort_order integer NOT NULL,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  label_fr text,
  label_ar text,
  CONSTRAINT academic_levels_pkey PRIMARY KEY (id),
  CONSTRAINT academic_levels_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id)
);
CREATE TABLE public.classes (
  id uuid NOT NULL DEFAULT gen_uuid(),
  tenant_id uuid NOT NULL,
  academic_year_id uuid NOT NULL,
  academic_level_id uuid NOT NULL,
  section text NOT NULL,
  code text NOT NULL,
  name text,
  capacity integer NOT NULL DEFAULT 30,
  homeroom_teacher_id uuid,
  room text,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  grade_code text,
  homeroom_teacher_name text,
  CONSTRAINT classes_pkey PRIMARY KEY (id),
  CONSTRAINT classes_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id),
  CONSTRAINT classes_academic_year_id_fkey FOREIGN KEY (academic_year_id) REFERENCES public.academic_years(id),
  CONSTRAINT classes_academic_level_id_fkey FOREIGN KEY (academic_level_id) REFERENCES public.academic_levels(id)
);
CREATE TABLE public.subjects (
  id uuid NOT NULL DEFAULT gen_uuid(),
  tenant_id uuid NOT NULL,
  code text NOT NULL,
  name_fr text NOT NULL,
  name_ar text,
  name_en text,
  domain text NOT NULL DEFAULT 'scolarite'::text CHECK (domain = ANY (ARRAY['scolarite'::text, 'club'::text, 'therapy'::text, 'auxiliary'::text])),
  default_coefficient integer NOT NULL DEFAULT 1 CHECK (default_coefficient > 0),
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  cycle text CHECK (cycle IS NULL OR (cycle = ANY (ARRAY['prescolaire'::text, 'primaire'::text, 'cem'::text, 'lycee'::text]))),
  passing_grade numeric DEFAULT 10.00 CHECK (passing_grade >= 0::numeric AND passing_grade <= 20::numeric),
  is_extracurricular boolean NOT NULL DEFAULT false,
  CONSTRAINT subjects_pkey PRIMARY KEY (id),
  CONSTRAINT subjects_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id)
);
CREATE TABLE public.class_subjects (
  id uuid NOT NULL DEFAULT gen_uuid(),
  tenant_id uuid NOT NULL,
  class_id uuid NOT NULL,
  subject_id uuid NOT NULL,
  teacher_id uuid,
  coefficient integer NOT NULL DEFAULT 1 CHECK (coefficient > 0),
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  teacher_name text,
  weekly_hours numeric DEFAULT 2.0 CHECK (weekly_hours > 0::numeric),
  CONSTRAINT class_subjects_pkey PRIMARY KEY (id),
  CONSTRAINT class_subjects_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id),
  CONSTRAINT class_subjects_class_id_fkey FOREIGN KEY (class_id) REFERENCES public.classes(id),
  CONSTRAINT class_subjects_subject_id_fkey FOREIGN KEY (subject_id) REFERENCES public.subjects(id)
);
CREATE TABLE public.assessments (
  id uuid NOT NULL DEFAULT gen_uuid(),
  tenant_id uuid NOT NULL,
  class_subject_id uuid NOT NULL,
  term integer NOT NULL CHECK (term = ANY (ARRAY[1, 2, 3])),
  kind text NOT NULL CHECK (kind = ANY (ARRAY['devoir_1'::text, 'devoir_2'::text, 'examen'::text])),
  label text,
  max_score numeric NOT NULL DEFAULT 20.00 CHECK (max_score > 0::numeric),
  weight numeric NOT NULL DEFAULT 1.00,
  scheduled_at date,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  student_id uuid,
  class_id uuid,
  subject_id uuid,
  academic_year text,
  devoir1 numeric CHECK (devoir1 IS NULL OR devoir1 >= 0::numeric AND devoir1 <= 20::numeric),
  devoir2 numeric CHECK (devoir2 IS NULL OR devoir2 >= 0::numeric AND devoir2 <= 20::numeric),
  examen numeric CHECK (examen IS NULL OR examen >= 0::numeric AND examen <= 20::numeric),
  subject_average numeric,
  coefficient numeric NOT NULL DEFAULT 1.00 CHECK (coefficient > 0::numeric),
  entered_by uuid,
  entered_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT assessments_pkey PRIMARY KEY (id),
  CONSTRAINT assessments_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id),
  CONSTRAINT assessments_class_subject_id_fkey FOREIGN KEY (class_subject_id) REFERENCES public.class_subjects(id),
  CONSTRAINT assessments_class_id_fkey FOREIGN KEY (class_id) REFERENCES public.classes(id),
  CONSTRAINT assessments_subject_id_fkey FOREIGN KEY (subject_id) REFERENCES public.subjects(id)
);
CREATE TABLE public.grades (
  id uuid NOT NULL DEFAULT gen_uuid(),
  tenant_id uuid NOT NULL,
  student_id uuid NOT NULL,
  assessment_id uuid NOT NULL,
  class_subject_id uuid NOT NULL,
  score numeric NOT NULL CHECK (score >= 0::numeric AND score <= 20::numeric),
  subject_average numeric CHECK (subject_average IS NULL OR subject_average >= 0::numeric AND subject_average <= 20::numeric),
  is_absent boolean NOT NULL DEFAULT false,
  entered_by uuid,
  entered_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT grades_pkey PRIMARY KEY (id),
  CONSTRAINT grades_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id),
  CONSTRAINT grades_assessment_id_fkey FOREIGN KEY (assessment_id) REFERENCES public.assessments(id),
  CONSTRAINT grades_class_subject_id_fkey FOREIGN KEY (class_subject_id) REFERENCES public.class_subjects(id)
);
CREATE TABLE public.attendance_records (
  id uuid NOT NULL DEFAULT gen_uuid(),
  tenant_id uuid NOT NULL,
  student_id uuid NOT NULL,
  class_id uuid NOT NULL,
  class_subject_id uuid,
  date date NOT NULL,
  status text NOT NULL CHECK (status = ANY (ARRAY['present'::text, 'absent_excused'::text, 'absent_unexcused'::text, 'late'::text])),
  arrival_time time without time zone,
  note text,
  recorded_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  record_date date,
  session text DEFAULT 'morning'::text CHECK (session = ANY (ARRAY['morning'::text, 'afternoon'::text, 'both'::text])),
  recorded_at timestamp with time zone NOT NULL DEFAULT now(),
  synced_at timestamp with time zone DEFAULT now(),
  CONSTRAINT attendance_records_pkey PRIMARY KEY (id),
  CONSTRAINT attendance_records_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id),
  CONSTRAINT attendance_records_class_id_fkey FOREIGN KEY (class_id) REFERENCES public.classes(id)
);
CREATE TABLE public.homework_assignments (
  id uuid NOT NULL DEFAULT gen_uuid(),
  tenant_id uuid NOT NULL,
  class_subject_id uuid NOT NULL,
  target_class_id uuid NOT NULL,
  title text NOT NULL,
  description text NOT NULL,
  attachment_path text,
  due_date date NOT NULL,
  created_by uuid NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT homework_assignments_pkey PRIMARY KEY (id),
  CONSTRAINT homework_assignments_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id),
  CONSTRAINT homework_assignments_class_subject_id_fkey FOREIGN KEY (class_subject_id) REFERENCES public.class_subjects(id),
  CONSTRAINT homework_assignments_target_class_id_fkey FOREIGN KEY (target_class_id) REFERENCES public.classes(id)
);
CREATE TABLE public.academic_history (
  id uuid NOT NULL DEFAULT gen_uuid(),
  tenant_id uuid NOT NULL,
  student_id uuid NOT NULL,
  academic_year_id uuid NOT NULL,
  academic_level_id uuid NOT NULL,
  class_id uuid,
  gpa numeric,
  decision text CHECK (decision = ANY (ARRAY['approved_for_promotion'::text, 'retained_same_year'::text, 'withdrawn'::text, 'graduated'::text])),
  subject_grades_json jsonb NOT NULL DEFAULT '{}'::jsonb,
  attendance_summary jsonb NOT NULL DEFAULT '{}'::jsonb,
  teacher_observations text,
  archived_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT academic_history_pkey PRIMARY KEY (id),
  CONSTRAINT academic_history_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id),
  CONSTRAINT academic_history_academic_year_id_fkey FOREIGN KEY (academic_year_id) REFERENCES public.academic_years(id),
  CONSTRAINT academic_history_academic_level_id_fkey FOREIGN KEY (academic_level_id) REFERENCES public.academic_levels(id),
  CONSTRAINT academic_history_class_id_fkey FOREIGN KEY (class_id) REFERENCES public.classes(id)
);
CREATE TABLE public.parents (
  id uuid NOT NULL DEFAULT gen_uuid(),
  tenant_id uuid NOT NULL,
  parent_code text NOT NULL,
  first_name text NOT NULL,
  last_name text NOT NULL,
  primary_phone text NOT NULL,
  secondary_phone text,
  email text,
  national_id text,
  occupation text,
  address text,
  city text,
  postal_code text,
  relationship text CHECK (relationship = ANY (ARRAY['father'::text, 'mother'::text, 'guardian'::text, 'other'::text])),
  notes text,
  is_active boolean NOT NULL DEFAULT true,
  is_financially_restricted boolean NOT NULL DEFAULT false,
  auth_user_id uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  deleted_at timestamp with time zone,
  display_name text,
  transport_destination text,
  city_tier text,
  CONSTRAINT parents_pkey PRIMARY KEY (id),
  CONSTRAINT parents_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id)
);
CREATE TABLE public.students (
  id uuid NOT NULL DEFAULT gen_uuid(),
  tenant_id uuid NOT NULL,
  parent_id uuid NOT NULL,
  student_code text NOT NULL,
  first_name text NOT NULL,
  middle_name text,
  last_name text NOT NULL,
  date_of_birth date NOT NULL,
  gender text CHECK (gender = ANY (ARRAY['male'::text, 'female'::text, 'other'::text])),
  grade_level_id uuid,
  class_id uuid,
  enrollment_date date NOT NULL DEFAULT CURRENT_DATE,
  enrollment_status text NOT NULL DEFAULT 'active'::text CHECK (enrollment_status = ANY (ARRAY['inquiry'::text, 'quoted'::text, 'enrolled'::text, 'active'::text, 'withdrawn'::text, 'graduated'::text])),
  medical_notes text,
  is_active boolean NOT NULL DEFAULT true,
  auth_user_id uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  deleted_at timestamp with time zone,
  display_name text,
  grade_level_code text,
  transport_tier text,
  payment_plan text NOT NULL DEFAULT 'tranches'::text CHECK (payment_plan = ANY (ARRAY['tranches'::text, 'full_annual'::text])),
  CONSTRAINT students_pkey PRIMARY KEY (id),
  CONSTRAINT students_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id),
  CONSTRAINT students_parent_id_fkey FOREIGN KEY (parent_id) REFERENCES public.parents(id),
  CONSTRAINT students_grade_level_id_fkey FOREIGN KEY (grade_level_id) REFERENCES public.academic_levels(id),
  CONSTRAINT students_class_id_fkey FOREIGN KEY (class_id) REFERENCES public.classes(id)
);
CREATE TABLE public.parent_student_links (
  id uuid NOT NULL DEFAULT gen_uuid(),
  tenant_id uuid NOT NULL,
  parent_id uuid NOT NULL,
  student_id uuid NOT NULL,
  relationship text CHECK (relationship = ANY (ARRAY['father'::text, 'mother'::text, 'guardian'::text, 'other'::text])),
  is_primary boolean NOT NULL DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT parent_student_links_pkey PRIMARY KEY (id),
  CONSTRAINT parent_student_links_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id),
  CONSTRAINT parent_student_links_parent_id_fkey FOREIGN KEY (parent_id) REFERENCES public.parents(id),
  CONSTRAINT parent_student_links_student_id_fkey FOREIGN KEY (student_id) REFERENCES public.students(id)
);
CREATE TABLE public.activation_codes (
  id uuid NOT NULL DEFAULT gen_uuid(),
  tenant_id uuid NOT NULL,
  code text NOT NULL,
  parent_id uuid,
  student_id uuid,
  issued_by uuid,
  issued_at timestamp with time zone NOT NULL DEFAULT now(),
  bound_to_auth_user_id uuid,
  bound_at timestamp with time zone,
  expires_at timestamp with time zone NOT NULL DEFAULT (now() + '30 days'::interval),
  CONSTRAINT activation_codes_pkey PRIMARY KEY (id),
  CONSTRAINT activation_codes_parent_id_fkey FOREIGN KEY (parent_id) REFERENCES public.parents(id),
  CONSTRAINT activation_codes_student_id_fkey FOREIGN KEY (student_id) REFERENCES public.students(id),
  CONSTRAINT activation_codes_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id)
);
CREATE TABLE public.student_documents (
  id uuid NOT NULL DEFAULT gen_uuid(),
  tenant_id uuid NOT NULL,
  student_id uuid NOT NULL,
  kind text NOT NULL CHECK (kind = ANY (ARRAY['birth_certificate'::text, 'medical_certificate'::text, 'contract'::text, 'justification_letter'::text, 'id_photo'::text, 'report_card'::text, 'other'::text])),
  file_name text NOT NULL,
  storage_path text NOT NULL,
  mime_type text,
  size_bytes bigint,
  uploaded_by uuid,
  uploaded_at timestamp with time zone NOT NULL DEFAULT now(),
  description text,
  CONSTRAINT student_documents_pkey PRIMARY KEY (id),
  CONSTRAINT student_documents_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id),
  CONSTRAINT student_documents_student_id_fkey FOREIGN KEY (student_id) REFERENCES public.students(id)
);
CREATE TABLE public.pricing_configs (
  id uuid NOT NULL DEFAULT gen_uuid(),
  tenant_id uuid NOT NULL,
  academic_year_id uuid NOT NULL,
  label text NOT NULL,
  registration_fee numeric NOT NULL DEFAULT 5000.00 CHECK (registration_fee >= 0::numeric),
  late_penalty_per_day numeric NOT NULL DEFAULT 100.00 CHECK (late_penalty_per_day >= 0::numeric),
  second_apron_fee numeric NOT NULL DEFAULT 2000.00 CHECK (second_apron_fee >= 0::numeric),
  early_payment_bonus_pct numeric NOT NULL DEFAULT 5.00 CHECK (early_payment_bonus_pct >= 0::numeric AND early_payment_bonus_pct <= 100::numeric),
  early_payment_deadline date,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT pricing_configs_pkey PRIMARY KEY (id),
  CONSTRAINT pricing_configs_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id),
  CONSTRAINT pricing_configs_academic_year_id_fkey FOREIGN KEY (academic_year_id) REFERENCES public.academic_years(id)
);
CREATE TABLE public.grade_level_tuition (
  id uuid NOT NULL DEFAULT gen_uuid(),
  pricing_config_id uuid NOT NULL,
  academic_level_id uuid NOT NULL,
  annual_amount numeric NOT NULL CHECK (annual_amount >= 0::numeric),
  tranche_1_amount numeric NOT NULL CHECK (tranche_1_amount >= 0::numeric),
  tranche_2_amount numeric NOT NULL CHECK (tranche_2_amount >= 0::numeric),
  tranche_3_amount numeric NOT NULL CHECK (tranche_3_amount >= 0::numeric),
  tranche_1_month integer NOT NULL DEFAULT 9 CHECK (tranche_1_month >= 1 AND tranche_1_month <= 12),
  tranche_2_month integer NOT NULL DEFAULT 12 CHECK (tranche_2_month >= 1 AND tranche_2_month <= 12),
  tranche_3_month integer NOT NULL CHECK (tranche_3_month >= 1 AND tranche_3_month <= 12),
  CONSTRAINT grade_level_tuition_pkey PRIMARY KEY (id),
  CONSTRAINT grade_level_tuition_pricing_config_id_fkey FOREIGN KEY (pricing_config_id) REFERENCES public.pricing_configs(id),
  CONSTRAINT grade_level_tuition_academic_level_id_fkey FOREIGN KEY (academic_level_id) REFERENCES public.academic_levels(id)
);
CREATE TABLE public.transport_destinations (
  id uuid NOT NULL DEFAULT gen_uuid(),
  pricing_config_id uuid NOT NULL,
  code text NOT NULL,
  label_fr text NOT NULL,
  label_ar text,
  annual_amount numeric NOT NULL CHECK (annual_amount >= 0::numeric),
  tranche_1_amount numeric NOT NULL CHECK (tranche_1_amount >= 0::numeric),
  tranche_2_amount numeric NOT NULL CHECK (tranche_2_amount >= 0::numeric),
  tranche_3_amount numeric NOT NULL CHECK (tranche_3_amount >= 0::numeric),
  tranche_1_month integer NOT NULL DEFAULT 9,
  tranche_2_month integer NOT NULL DEFAULT 12,
  tranche_3_month integer NOT NULL DEFAULT 3,
  CONSTRAINT transport_destinations_pkey PRIMARY KEY (id),
  CONSTRAINT transport_destinations_pricing_config_id_fkey FOREIGN KEY (pricing_config_id) REFERENCES public.pricing_configs(id)
);
CREATE TABLE public.complementary_services (
  id uuid NOT NULL DEFAULT gen_uuid(),
  pricing_config_id uuid NOT NULL,
  code text NOT NULL,
  label_fr text NOT NULL,
  label_ar text,
  semester_amount numeric,
  annual_amount numeric,
  billing_model text NOT NULL DEFAULT 'per_session'::text CHECK (billing_model = ANY (ARRAY['per_session'::text, 'per_semester'::text, 'per_year'::text, 'per_term'::text])),
  is_active boolean NOT NULL DEFAULT true,
  CONSTRAINT complementary_services_pkey PRIMARY KEY (id),
  CONSTRAINT complementary_services_pricing_config_id_fkey FOREIGN KEY (pricing_config_id) REFERENCES public.pricing_configs(id)
);
CREATE TABLE public.additional_services (
  id uuid NOT NULL DEFAULT gen_uuid(),
  pricing_config_id uuid NOT NULL,
  code text NOT NULL,
  label_fr text NOT NULL,
  label_ar text,
  amount numeric NOT NULL CHECK (amount >= 0::numeric),
  billing_model text NOT NULL DEFAULT 'one_time'::text CHECK (billing_model = ANY (ARRAY['one_time'::text, 'per_month'::text, 'per_term'::text, 'per_year'::text])),
  is_active boolean NOT NULL DEFAULT true,
  CONSTRAINT additional_services_pkey PRIMARY KEY (id),
  CONSTRAINT additional_services_pricing_config_id_fkey FOREIGN KEY (pricing_config_id) REFERENCES public.pricing_configs(id)
);
CREATE TABLE public.discounts (
  id uuid NOT NULL DEFAULT gen_uuid(),
  pricing_config_id uuid NOT NULL,
  code text NOT NULL CHECK (code = ANY (ARRAY['passage_palier'::text, 'seniority_5y'::text, 'full_annual'::text, 'highest_average'::text, 'sibling_fixed'::text])),
  label_fr text NOT NULL,
  label_ar text,
  discount_type text NOT NULL CHECK (discount_type = ANY (ARRAY['fixed_amount'::text, 'percentage'::text])),
  amount numeric NOT NULL CHECK (amount >= 0::numeric),
  applies_to text NOT NULL DEFAULT 'total'::text CHECK (applies_to = ANY (ARRAY['tuition'::text, 'transport'::text, 'total'::text, 'per_student'::text])),
  is_active boolean NOT NULL DEFAULT true,
  CONSTRAINT discounts_pkey PRIMARY KEY (id),
  CONSTRAINT discounts_pricing_config_id_fkey FOREIGN KEY (pricing_config_id) REFERENCES public.pricing_configs(id)
);
CREATE TABLE public.discount_applications (
  id uuid NOT NULL DEFAULT gen_uuid(),
  tenant_id uuid NOT NULL,
  student_id uuid NOT NULL,
  discount_id uuid NOT NULL,
  amount_applied numeric NOT NULL CHECK (amount_applied >= 0::numeric),
  reason_note text,
  applied_by uuid,
  applied_at timestamp with time zone NOT NULL DEFAULT now(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT discount_applications_pkey PRIMARY KEY (id),
  CONSTRAINT discount_applications_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id),
  CONSTRAINT discount_applications_student_id_fkey FOREIGN KEY (student_id) REFERENCES public.students(id),
  CONSTRAINT discount_applications_discount_id_fkey FOREIGN KEY (discount_id) REFERENCES public.discounts(id)
);
CREATE TABLE public.service_enrollments (
  id uuid NOT NULL DEFAULT gen_uuid(),
  tenant_id uuid NOT NULL,
  student_id uuid NOT NULL,
  academic_year_id uuid NOT NULL,
  service_kind text NOT NULL CHECK (service_kind = ANY (ARRAY['tuition'::text, 'transport'::text, 'canteen'::text, 'club'::text, 'speech_therapy'::text, 'psychology'::text, 'psychotherapy'::text, 'second_apron'::text, 'rattrapage'::text, 'other'::text])),
  service_ref_id uuid,
  destination_id uuid,
  grade_level_id uuid,
  annual_amount numeric NOT NULL CHECK (annual_amount >= 0::numeric),
  tranche_1_amount numeric NOT NULL DEFAULT 0,
  tranche_2_amount numeric NOT NULL DEFAULT 0,
  tranche_3_amount numeric NOT NULL DEFAULT 0,
  tranche_1_due_date date,
  tranche_2_due_date date,
  tranche_3_due_date date,
  is_active boolean NOT NULL DEFAULT true,
  enrolled_at timestamp with time zone NOT NULL DEFAULT now(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT service_enrollments_pkey PRIMARY KEY (id),
  CONSTRAINT service_enrollments_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id),
  CONSTRAINT service_enrollments_student_id_fkey FOREIGN KEY (student_id) REFERENCES public.students(id),
  CONSTRAINT service_enrollments_academic_year_id_fkey FOREIGN KEY (academic_year_id) REFERENCES public.academic_years(id),
  CONSTRAINT service_enrollments_destination_id_fkey FOREIGN KEY (destination_id) REFERENCES public.transport_destinations(id),
  CONSTRAINT service_enrollments_grade_level_id_fkey FOREIGN KEY (grade_level_id) REFERENCES public.academic_levels(id)
);
CREATE TABLE public.invoices (
  id uuid NOT NULL DEFAULT gen_uuid(),
  tenant_id uuid NOT NULL,
  parent_id uuid NOT NULL,
  student_id uuid,
  service_enrollment_id uuid,
  invoice_number text NOT NULL,
  issue_date date NOT NULL DEFAULT CURRENT_DATE,
  due_date date NOT NULL,
  amount numeric NOT NULL CHECK (amount >= 0::numeric),
  status text NOT NULL DEFAULT 'unpaid'::text CHECK (status = ANY (ARRAY['unpaid'::text, 'paid'::text, 'partial'::text, 'cancelled'::text, 'overdue'::text])),
  paid_amount numeric NOT NULL DEFAULT 0,
  notes text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT invoices_pkey PRIMARY KEY (id),
  CONSTRAINT invoices_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id),
  CONSTRAINT invoices_parent_id_fkey FOREIGN KEY (parent_id) REFERENCES public.parents(id),
  CONSTRAINT invoices_student_id_fkey FOREIGN KEY (student_id) REFERENCES public.students(id),
  CONSTRAINT invoices_service_enrollment_id_fkey FOREIGN KEY (service_enrollment_id) REFERENCES public.service_enrollments(id)
);
CREATE TABLE public.installments (
  id uuid NOT NULL DEFAULT gen_uuid(),
  tenant_id uuid NOT NULL,
  parent_id uuid NOT NULL,
  student_id uuid NOT NULL,
  service_enrollment_id uuid,
  invoice_id uuid,
  tranche_number integer NOT NULL CHECK (tranche_number = ANY (ARRAY[1, 2, 3])),
  amount_due numeric NOT NULL CHECK (amount_due >= 0::numeric),
  amount_paid numeric NOT NULL DEFAULT 0 CHECK (amount_paid >= 0::numeric),
  due_date date NOT NULL,
  paid_date date,
  status text NOT NULL DEFAULT 'unpaid'::text CHECK (status = ANY (ARRAY['unpaid'::text, 'partial'::text, 'paid'::text, 'overdue'::text, 'pending_clearance'::text])),
  academic_cycle text CHECK (academic_cycle = ANY (ARRAY['primaire'::text, 'cem'::text, 'lycee'::text, 'prescolaire'::text])),
  is_custom_schedule boolean NOT NULL DEFAULT false,
  custom_schedule_note text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  amount_pending numeric NOT NULL DEFAULT 0.00,
  payment_plan text NOT NULL DEFAULT 'tranches'::text CHECK (payment_plan = ANY (ARRAY['full_annual'::text, 'tranches'::text])),
  label text,
  category text NOT NULL DEFAULT 'tuition'::text CHECK (category = ANY (ARRAY['tuition'::text, 'transport'::text, 'canteen'::text, 'uniform'::text, 'books'::text, 'extracurricular'::text, 'therapy_psychology'::text, 'therapy_speech'::text, 'second_apron'::text, 'parent_credit'::text, 'other'::text])),
  source_type text,
  source_id text,
  CONSTRAINT installments_pkey PRIMARY KEY (id),
  CONSTRAINT installments_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id),
  CONSTRAINT installments_parent_id_fkey FOREIGN KEY (parent_id) REFERENCES public.parents(id),
  CONSTRAINT installments_student_id_fkey FOREIGN KEY (student_id) REFERENCES public.students(id),
  CONSTRAINT installments_service_enrollment_id_fkey FOREIGN KEY (service_enrollment_id) REFERENCES public.service_enrollments(id),
  CONSTRAINT installments_invoice_id_fkey FOREIGN KEY (invoice_id) REFERENCES public.invoices(id)
);
CREATE TABLE public.payments (
  id uuid NOT NULL DEFAULT gen_uuid(),
  tenant_id uuid NOT NULL,
  payment_number text NOT NULL,
  parent_id uuid NOT NULL,
  student_id uuid,
  invoice_id uuid,
  installment_id uuid,
  amount numeric NOT NULL CHECK (amount > 0::numeric),
  method text NOT NULL CHECK (method = ANY (ARRAY['cash'::text, 'check'::text, 'transfer'::text])),
  check_number text,
  check_bank_name text,
  check_issue_date date,
  check_clearance_date date,
  transfer_reference text,
  transfer_source_bank text,
  proof_path text,
  status text NOT NULL CHECK (status = ANY (ARRAY['paid'::text, 'pending'::text, 'unpaid'::text, 'refunded'::text, 'cancelled'::text])),
  collected_at timestamp with time zone NOT NULL DEFAULT now(),
  collected_by uuid,
  notes text,
  reversal_of_payment_id uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  receipt_number text,
  category text NOT NULL DEFAULT 'other'::text CHECK (category = ANY (ARRAY['tuition'::text, 'transport'::text, 'canteen'::text, 'uniform'::text, 'books'::text, 'extracurricular'::text, 'therapy_psychology'::text, 'therapy_speech'::text, 'second_apron'::text, 'parent_credit'::text, 'other'::text])),
  CONSTRAINT payments_pkey PRIMARY KEY (id),
  CONSTRAINT payments_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id),
  CONSTRAINT payments_parent_id_fkey FOREIGN KEY (parent_id) REFERENCES public.parents(id),
  CONSTRAINT payments_student_id_fkey FOREIGN KEY (student_id) REFERENCES public.students(id),
  CONSTRAINT payments_invoice_id_fkey FOREIGN KEY (invoice_id) REFERENCES public.invoices(id),
  CONSTRAINT payments_installment_id_fkey FOREIGN KEY (installment_id) REFERENCES public.installments(id)
);
CREATE TABLE public.account_adjustments (
  id uuid NOT NULL DEFAULT gen_uuid(),
  tenant_id uuid NOT NULL,
  parent_id uuid,
  student_id uuid,
  amount numeric NOT NULL CHECK (amount <> 0::numeric),
  reason_code text NOT NULL CHECK (reason_code = ANY (ARRAY['sibling_discount'::text, 'staff_family'::text, 'early_payment'::text, 'passage_palier'::text, 'seniority_5y'::text, 'highest_average'::text, 'full_annual'::text, 'scholarship_replacement'::text, 'hardship'::text, 'correction'::text, 'late_fee_waiver'::text, 'other'::text])),
  admin_note text NOT NULL,
  performed_by uuid NOT NULL,
  performed_at timestamp with time zone NOT NULL DEFAULT now(),
  before_json jsonb NOT NULL,
  after_json jsonb NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT account_adjustments_pkey PRIMARY KEY (id),
  CONSTRAINT account_adjustments_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id),
  CONSTRAINT account_adjustments_parent_id_fkey FOREIGN KEY (parent_id) REFERENCES public.parents(id),
  CONSTRAINT account_adjustments_student_id_fkey FOREIGN KEY (student_id) REFERENCES public.students(id)
);
CREATE TABLE public.receipts (
  id uuid NOT NULL DEFAULT gen_uuid(),
  tenant_id uuid NOT NULL,
  receipt_number text NOT NULL,
  receipt_kind text NOT NULL CHECK (receipt_kind = ANY (ARRAY['recent_payment'::text, 'account_statement'::text])),
  payment_id uuid,
  parent_id uuid NOT NULL,
  pdf_path text NOT NULL,
  pdf_size_bytes bigint,
  generated_at timestamp with time zone NOT NULL DEFAULT now(),
  generated_by uuid,
  CONSTRAINT receipts_pkey PRIMARY KEY (id),
  CONSTRAINT receipts_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id),
  CONSTRAINT receipts_payment_id_fkey FOREIGN KEY (payment_id) REFERENCES public.payments(id),
  CONSTRAINT receipts_parent_id_fkey FOREIGN KEY (parent_id) REFERENCES public.parents(id)
);
CREATE TABLE public.ledger_entries (
  id uuid NOT NULL DEFAULT gen_uuid(),
  tenant_id uuid NOT NULL,
  entry_number text NOT NULL,
  parent_id uuid NOT NULL,
  student_id uuid,
  service_enrollment_id uuid,
  payment_id uuid,
  adjustment_id uuid,
  reverses_entry_id uuid,
  account_id text NOT NULL,
  entry_type text NOT NULL CHECK (entry_type = ANY (ARRAY['charge'::text, 'payment'::text, 'adjustment'::text, 'refund'::text, 'reversal'::text, 'transfer'::text])),
  amount numeric NOT NULL CHECK (amount <> 0::numeric),
  category text NOT NULL CHECK (category = ANY (ARRAY['tuition'::text, 'transport'::text, 'canteen'::text, 'uniform'::text, 'books'::text, 'extracurricular'::text, 'therapy_psychology'::text, 'therapy_speech'::text, 'second_apron'::text, 'parent_credit'::text, 'other'::text])),
  description text,
  entry_date timestamp with time zone NOT NULL DEFAULT now(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  source_type text,
  source_id text,
  method text CHECK (method IS NULL OR (method = ANY (ARRAY['cash'::text, 'check'::text, 'transfer'::text]))),
  receipt_number text,
  payment_status text,
  reverses_id text,
  actor_id text,
  actor_name text,
  at timestamp with time zone,
  metadata jsonb,
  CONSTRAINT ledger_entries_pkey PRIMARY KEY (id),
  CONSTRAINT ledger_entries_reverses_entry_id_fkey FOREIGN KEY (reverses_entry_id) REFERENCES public.ledger_entries(id),
  CONSTRAINT ledger_entries_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id),
  CONSTRAINT ledger_entries_parent_id_fkey FOREIGN KEY (parent_id) REFERENCES public.parents(id),
  CONSTRAINT ledger_entries_student_id_fkey FOREIGN KEY (student_id) REFERENCES public.students(id),
  CONSTRAINT ledger_entries_service_enrollment_id_fkey FOREIGN KEY (service_enrollment_id) REFERENCES public.service_enrollments(id),
  CONSTRAINT ledger_entries_payment_id_fkey FOREIGN KEY (payment_id) REFERENCES public.payments(id),
  CONSTRAINT ledger_entries_adjustment_id_fkey FOREIGN KEY (adjustment_id) REFERENCES public.account_adjustments(id)
);
CREATE TABLE public.expense_categories (
  id uuid NOT NULL DEFAULT gen_uuid(),
  tenant_id uuid NOT NULL,
  code text NOT NULL CHECK (code = ANY (ARRAY['maintenance'::text, 'office_supplies'::text, 'educational_material'::text, 'utilities'::text, 'transport'::text, 'it'::text, 'facilities'::text, 'medical'::text, 'other'::text])),
  label_fr text NOT NULL,
  label_ar text,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT expense_categories_pkey PRIMARY KEY (id),
  CONSTRAINT expense_categories_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id)
);
CREATE TABLE public.expense_tickets (
  id uuid NOT NULL DEFAULT gen_uuid(),
  tenant_id uuid NOT NULL,
  ticket_number text NOT NULL,
  title text NOT NULL,
  description text NOT NULL,
  category_id uuid NOT NULL,
  requested_amount numeric NOT NULL CHECK (requested_amount > 0::numeric),
  final_spent_amount numeric CHECK (final_spent_amount IS NULL OR final_spent_amount >= 0::numeric),
  justification text NOT NULL,
  urgency text NOT NULL CHECK (urgency = ANY (ARRAY['low'::text, 'medium'::text, 'high'::text, 'critical'::text])),
  status text NOT NULL DEFAULT 'pending_approval'::text CHECK (status = ANY (ARRAY['draft'::text, 'pending_approval'::text, 'approved_funds_released'::text, 'rejected'::text, 'disbursed'::text, 'settled_and_closed'::text])),
  submitted_by uuid NOT NULL,
  submitted_at timestamp with time zone NOT NULL DEFAULT now(),
  approved_by uuid,
  approved_at timestamp with time zone,
  approval_note text,
  rejected_reason text,
  disbursed_at timestamp with time zone,
  settled_by uuid,
  settled_at timestamp with time zone,
  receipt_path text,
  receipt_uploaded_at timestamp with time zone,
  receipt_uploaded_by uuid,
  anomaly_score numeric,
  anomaly_flags_json jsonb NOT NULL DEFAULT '[]'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT expense_tickets_pkey PRIMARY KEY (id),
  CONSTRAINT expense_tickets_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id),
  CONSTRAINT expense_tickets_category_id_fkey FOREIGN KEY (category_id) REFERENCES public.expense_categories(id)
);
CREATE TABLE public.expense_state_transitions (
  id uuid NOT NULL DEFAULT gen_uuid(),
  tenant_id uuid NOT NULL,
  ticket_id uuid NOT NULL,
  from_status text NOT NULL,
  to_status text NOT NULL,
  actor_id uuid NOT NULL,
  actor_note text,
  transitioned_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT expense_state_transitions_pkey PRIMARY KEY (id),
  CONSTRAINT expense_state_transitions_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id),
  CONSTRAINT expense_state_transitions_ticket_id_fkey FOREIGN KEY (ticket_id) REFERENCES public.expense_tickets(id)
);
CREATE TABLE public.personnel (
  id uuid NOT NULL DEFAULT gen_uuid(),
  tenant_id uuid NOT NULL,
  personnel_code text NOT NULL,
  user_id uuid,
  first_name text NOT NULL,
  last_name text NOT NULL,
  middle_name text,
  date_of_birth date,
  gender text CHECK (gender = ANY (ARRAY['male'::text, 'female'::text, 'other'::text])),
  national_id text,
  staff_category text NOT NULL CHECK (staff_category = ANY (ARRAY['administration'::text, 'teaching'::text, 'support'::text, 'medical'::text])),
  role_id uuid,
  department_id uuid,
  supervisor_id uuid,
  position text,
  hire_date date NOT NULL DEFAULT CURRENT_DATE,
  end_date date,
  is_active boolean NOT NULL DEFAULT true,
  base_salary numeric,
  payment_method text CHECK (payment_method = ANY (ARRAY['cash'::text, 'bank_transfer'::text, 'check'::text])),
  bank_account text,
  bonuses_json jsonb NOT NULL DEFAULT '[]'::jsonb,
  primary_phone text,
  secondary_phone text,
  email text,
  address text,
  emergency_contact jsonb NOT NULL DEFAULT '{}'::jsonb,
  documents_json jsonb NOT NULL DEFAULT '[]'::jsonb,
  notes text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  deleted_at timestamp with time zone,
  CONSTRAINT personnel_pkey PRIMARY KEY (id),
  CONSTRAINT personnel_department_fk FOREIGN KEY (department_id) REFERENCES public.departments(id),
  CONSTRAINT personnel_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id),
  CONSTRAINT personnel_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.user_profiles(id),
  CONSTRAINT personnel_role_id_fkey FOREIGN KEY (role_id) REFERENCES public.roles(id),
  CONSTRAINT personnel_supervisor_id_fkey FOREIGN KEY (supervisor_id) REFERENCES public.personnel(id)
);
CREATE TABLE public.releve_entries (
  id uuid NOT NULL DEFAULT gen_uuid(),
  tenant_id uuid NOT NULL,
  personnel_id uuid NOT NULL,
  activity_type text NOT NULL CHECK (activity_type = ANY (ARRAY['course'::text, 'meeting'::text, 'surveillance'::text, 'correction'::text, 'task'::text, 'delivery'::text, 'warehouse'::text, 'admin'::text, 'other'::text])),
  class_id uuid,
  class_subject_id uuid,
  description text,
  clock_in_at timestamp with time zone NOT NULL,
  clock_out_at timestamp with time zone,
  duration_minutes integer DEFAULT 
CASE
    WHEN (clock_out_at IS NOT NULL) THEN ((EXTRACT(epoch FROM (clock_out_at - clock_in_at)))::integer / 60)
    ELSE NULL::integer
END,
  recorded_by uuid NOT NULL,
  recorded_at timestamp with time zone NOT NULL DEFAULT now(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT releve_entries_pkey PRIMARY KEY (id),
  CONSTRAINT releve_entries_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id),
  CONSTRAINT releve_entries_personnel_id_fkey FOREIGN KEY (personnel_id) REFERENCES public.personnel(id),
  CONSTRAINT releve_entries_class_id_fkey FOREIGN KEY (class_id) REFERENCES public.classes(id),
  CONSTRAINT releve_entries_class_subject_id_fkey FOREIGN KEY (class_subject_id) REFERENCES public.class_subjects(id)
);
CREATE TABLE public.departments (
  id uuid NOT NULL DEFAULT gen_uuid(),
  tenant_id uuid NOT NULL,
  code text NOT NULL,
  name_fr text NOT NULL,
  label_ar text,
  color_hex text CHECK (color_hex ~ '^#[0-9A-Fa-f]{6}$'::text),
  head_personnel_id uuid,
  description text,
  sort_order integer NOT NULL DEFAULT 0,
  is_active boolean NOT NULL DEFAULT true,
  is_archived boolean NOT NULL DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT departments_pkey PRIMARY KEY (id),
  CONSTRAINT departments_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id),
  CONSTRAINT departments_head_personnel_id_fkey FOREIGN KEY (head_personnel_id) REFERENCES public.personnel(id)
);
CREATE TABLE public.shifts (
  id uuid NOT NULL DEFAULT gen_uuid(),
  tenant_id uuid NOT NULL,
  code text NOT NULL,
  name text NOT NULL,
  start_time time without time zone NOT NULL,
  end_time time without time zone NOT NULL,
  grace_period_minutes integer NOT NULL DEFAULT 0 CHECK (grace_period_minutes >= 0),
  color_hex text CHECK (color_hex ~ '^#[0-9A-Fa-f]{6}$'::text),
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT shifts_pkey PRIMARY KEY (id),
  CONSTRAINT shifts_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id)
);
CREATE TABLE public.schedules (
  id uuid NOT NULL DEFAULT gen_uuid(),
  tenant_id uuid NOT NULL,
  personnel_id uuid NOT NULL,
  shift_id uuid,
  date date NOT NULL,
  start_time time without time zone,
  end_time time without time zone,
  note text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT schedules_pkey PRIMARY KEY (id),
  CONSTRAINT schedules_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id),
  CONSTRAINT schedules_personnel_id_fkey FOREIGN KEY (personnel_id) REFERENCES public.personnel(id),
  CONSTRAINT schedules_shift_id_fkey FOREIGN KEY (shift_id) REFERENCES public.shifts(id)
);
CREATE TABLE public.tasks (
  id uuid NOT NULL DEFAULT gen_uuid(),
  tenant_id uuid NOT NULL,
  title text NOT NULL CHECK (length(TRIM(BOTH FROM title)) >= 1),
  description text,
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'assigned'::text, 'in_progress'::text, 'blocked'::text, 'completed'::text, 'cancelled'::text])),
  priority text NOT NULL DEFAULT 'medium'::text CHECK (priority = ANY (ARRAY['low'::text, 'medium'::text, 'high'::text, 'urgent'::text])),
  department_id uuid,
  assignee_ids jsonb NOT NULL DEFAULT '[]'::jsonb,
  due_date date,
  completed_at timestamp with time zone,
  progress integer NOT NULL DEFAULT 0 CHECK (progress >= 0 AND progress <= 100),
  tags ARRAY NOT NULL DEFAULT '{}'::text[],
  created_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT tasks_pkey PRIMARY KEY (id),
  CONSTRAINT tasks_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id),
  CONSTRAINT tasks_department_id_fkey FOREIGN KEY (department_id) REFERENCES public.departments(id)
);
CREATE TABLE public.task_comments (
  id uuid NOT NULL DEFAULT gen_uuid(),
  tenant_id uuid NOT NULL,
  task_id uuid NOT NULL,
  author_id uuid NOT NULL,
  body text NOT NULL CHECK (length(TRIM(BOTH FROM body)) >= 1),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT task_comments_pkey PRIMARY KEY (id),
  CONSTRAINT task_comments_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id),
  CONSTRAINT task_comments_task_id_fkey FOREIGN KEY (task_id) REFERENCES public.tasks(id)
);
CREATE TABLE public.task_attachments (
  id uuid NOT NULL DEFAULT gen_uuid(),
  tenant_id uuid NOT NULL,
  task_id uuid NOT NULL,
  file_name text NOT NULL,
  storage_path text NOT NULL,
  mime_type text,
  size_bytes bigint CHECK (size_bytes IS NULL OR size_bytes >= 0),
  uploaded_by uuid NOT NULL,
  uploaded_at timestamp with time zone NOT NULL DEFAULT now(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT task_attachments_pkey PRIMARY KEY (id),
  CONSTRAINT task_attachments_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id),
  CONSTRAINT task_attachments_task_id_fkey FOREIGN KEY (task_id) REFERENCES public.tasks(id)
);
CREATE TABLE public.workforce_attendance_events (
  id uuid NOT NULL DEFAULT gen_uuid(),
  tenant_id uuid NOT NULL,
  personnel_id uuid NOT NULL,
  event_type text NOT NULL CHECK (event_type = ANY (ARRAY['clock_in'::text, 'break_start'::text, 'break_end'::text, 'clock_out'::text])),
  event_at timestamp with time zone NOT NULL DEFAULT now(),
  latitude numeric,
  longitude numeric,
  note text,
  recorded_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT workforce_attendance_events_pkey PRIMARY KEY (id),
  CONSTRAINT workforce_attendance_events_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id),
  CONSTRAINT workforce_attendance_events_personnel_id_fkey FOREIGN KEY (personnel_id) REFERENCES public.personnel(id)
);
CREATE TABLE public.leave_requests (
  id uuid NOT NULL DEFAULT gen_uuid(),
  tenant_id uuid NOT NULL,
  personnel_id uuid NOT NULL,
  leave_type text NOT NULL CHECK (leave_type = ANY (ARRAY['annual'::text, 'sick'::text, 'personal'::text, 'unpaid'::text, 'maternity'::text, 'paternity'::text])),
  start_date date NOT NULL,
  end_date date NOT NULL,
  reason text,
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'approved'::text, 'rejected'::text, 'cancelled'::text])),
  reviewed_by uuid,
  reviewed_at timestamp with time zone,
  decision_note text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT leave_requests_pkey PRIMARY KEY (id),
  CONSTRAINT leave_requests_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id),
  CONSTRAINT leave_requests_personnel_id_fkey FOREIGN KEY (personnel_id) REFERENCES public.personnel(id)
);
CREATE TABLE public.performance_reviews (
  id uuid NOT NULL DEFAULT gen_uuid(),
  tenant_id uuid NOT NULL,
  personnel_id uuid NOT NULL,
  review_period text NOT NULL CHECK (review_period = ANY (ARRAY['q1'::text, 'q2'::text, 'q3'::text, 'q4'::text, 'annual'::text])),
  reviewer_id uuid,
  score numeric CHECK (score IS NULL OR score >= 0::numeric AND score <= 10::numeric),
  strengths text,
  areas_for_improvement text,
  goals text,
  review_date date NOT NULL DEFAULT CURRENT_DATE,
  status text NOT NULL DEFAULT 'draft'::text CHECK (status = ANY (ARRAY['draft'::text, 'published'::text, 'acknowledged'::text])),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT performance_reviews_pkey PRIMARY KEY (id),
  CONSTRAINT performance_reviews_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id),
  CONSTRAINT performance_reviews_personnel_id_fkey FOREIGN KEY (personnel_id) REFERENCES public.personnel(id),
  CONSTRAINT performance_reviews_reviewer_id_fkey FOREIGN KEY (reviewer_id) REFERENCES public.personnel(id)
);
CREATE TABLE public.chat_channels (
  id uuid NOT NULL DEFAULT gen_uuid(),
  tenant_id uuid NOT NULL,
  code text NOT NULL,
  name text NOT NULL,
  channel_type text NOT NULL CHECK (channel_type = ANY (ARRAY['direct'::text, 'group'::text, 'department'::text, 'announcement'::text])),
  member_ids ARRAY NOT NULL DEFAULT '{}'::uuid[],
  created_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT chat_channels_pkey PRIMARY KEY (id),
  CONSTRAINT chat_channels_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id)
);
CREATE TABLE public.chat_messages (
  id uuid NOT NULL DEFAULT gen_uuid(),
  tenant_id uuid NOT NULL,
  channel_id uuid NOT NULL,
  author_id uuid NOT NULL,
  body text NOT NULL DEFAULT ''::text,
  edited_at timestamp with time zone,
  edited_by uuid,
  deleted_at timestamp with time zone,
  parent_message_id uuid,
  read_by jsonb NOT NULL DEFAULT '[]'::jsonb,
  attachments jsonb NOT NULL DEFAULT '[]'::jsonb,
  sent_at timestamp with time zone NOT NULL DEFAULT now(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT chat_messages_pkey PRIMARY KEY (id),
  CONSTRAINT chat_messages_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id),
  CONSTRAINT chat_messages_channel_id_fkey FOREIGN KEY (channel_id) REFERENCES public.chat_channels(id),
  CONSTRAINT chat_messages_parent_message_id_fkey FOREIGN KEY (parent_message_id) REFERENCES public.chat_messages(id)
);
CREATE TABLE public.onboarding_states (
  id uuid NOT NULL DEFAULT gen_uuid(),
  tenant_id uuid NOT NULL,
  personnel_id uuid NOT NULL,
  current_step integer NOT NULL DEFAULT 0 CHECK (current_step >= 0),
  completed_steps ARRAY NOT NULL DEFAULT '{}'::integer[],
  started_at timestamp with time zone NOT NULL DEFAULT now(),
  completed_at timestamp with time zone,
  data_json jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT onboarding_states_pkey PRIMARY KEY (id),
  CONSTRAINT onboarding_states_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id),
  CONSTRAINT onboarding_states_personnel_id_fkey FOREIGN KEY (personnel_id) REFERENCES public.personnel(id)
);
CREATE TABLE public.suppliers (
  id uuid NOT NULL DEFAULT gen_uuid(),
  tenant_id uuid NOT NULL,
  code text NOT NULL,
  name text NOT NULL,
  contact_name text,
  phone text,
  email text,
  address text,
  tax_id text,
  payment_terms text,
  rating smallint CHECK (rating IS NULL OR rating >= 1 AND rating <= 5),
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  deleted_at timestamp with time zone,
  CONSTRAINT suppliers_pkey PRIMARY KEY (id),
  CONSTRAINT suppliers_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id)
);
CREATE TABLE public.purchase_requests (
  id uuid NOT NULL DEFAULT gen_uuid(),
  tenant_id uuid NOT NULL,
  request_number text NOT NULL,
  title text NOT NULL,
  description text,
  requester_id uuid NOT NULL,
  department_id uuid,
  status text NOT NULL DEFAULT 'draft'::text CHECK (status = ANY (ARRAY['draft'::text, 'submitted'::text, 'approved'::text, 'rejected'::text, 'ordered'::text, 'received'::text, 'cancelled'::text])),
  priority text NOT NULL DEFAULT 'medium'::text CHECK (priority = ANY (ARRAY['low'::text, 'medium'::text, 'high'::text, 'urgent'::text])),
  expected_delivery_date date,
  total_amount numeric NOT NULL DEFAULT 0 CHECK (total_amount >= 0::numeric),
  lines jsonb NOT NULL DEFAULT '[]'::jsonb,
  approved_by uuid,
  approved_at timestamp with time zone,
  rejected_reason text,
  supplier_id uuid,
  ordered_at timestamp with time zone,
  received_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT purchase_requests_pkey PRIMARY KEY (id),
  CONSTRAINT purchase_requests_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id),
  CONSTRAINT purchase_requests_department_id_fkey FOREIGN KEY (department_id) REFERENCES public.departments(id),
  CONSTRAINT purchase_requests_supplier_id_fkey FOREIGN KEY (supplier_id) REFERENCES public.suppliers(id)
);
CREATE TABLE public.deliveries (
  id uuid NOT NULL DEFAULT gen_uuid(),
  tenant_id uuid NOT NULL,
  delivery_number text NOT NULL,
  delivery_type text NOT NULL CHECK (delivery_type = ANY (ARRAY['inbound'::text, 'outbound'::text, 'internal'::text])),
  status text NOT NULL DEFAULT 'assigned'::text CHECK (status = ANY (ARRAY['assigned'::text, 'in_transit'::text, 'delivered'::text, 'confirmed'::text, 'failed'::text, 'cancelled'::text])),
  driver_id uuid,
  vehicle text,
  origin_address text,
  destination_address text,
  scheduled_at timestamp with time zone NOT NULL,
  departed_at timestamp with time zone,
  delivered_at timestamp with time zone,
  confirmed_at timestamp with time zone,
  stops jsonb NOT NULL DEFAULT '[]'::jsonb,
  notes text,
  delay_reason text,
  delay_minutes integer NOT NULL DEFAULT 0 CHECK (delay_minutes >= 0),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT deliveries_pkey PRIMARY KEY (id),
  CONSTRAINT deliveries_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id),
  CONSTRAINT deliveries_driver_id_fkey FOREIGN KEY (driver_id) REFERENCES public.personnel(id)
);
CREATE TABLE public.inventory_items (
  id uuid NOT NULL DEFAULT gen_uuid(),
  tenant_id uuid NOT NULL,
  sku text NOT NULL,
  name text NOT NULL,
  description text,
  category text,
  unit text NOT NULL DEFAULT 'piece'::text,
  quantity_on_hand numeric NOT NULL DEFAULT 0 CHECK (quantity_on_hand >= 0::numeric),
  quantity_reserved numeric NOT NULL DEFAULT 0 CHECK (quantity_reserved >= 0::numeric),
  reorder_level numeric NOT NULL DEFAULT 0 CHECK (reorder_level >= 0::numeric),
  reorder_quantity numeric NOT NULL DEFAULT 0 CHECK (reorder_quantity >= 0::numeric),
  unit_cost numeric NOT NULL DEFAULT 0 CHECK (unit_cost >= 0::numeric),
  location text,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  deleted_at timestamp with time zone,
  CONSTRAINT inventory_items_pkey PRIMARY KEY (id),
  CONSTRAINT inventory_items_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id)
);
CREATE TABLE public.inventory_transactions (
  id uuid NOT NULL DEFAULT gen_uuid(),
  tenant_id uuid NOT NULL,
  item_id uuid NOT NULL,
  transaction_type text NOT NULL CHECK (transaction_type = ANY (ARRAY['receive'::text, 'dispatch'::text, 'scan'::text, 'damage'::text, 'adjust'::text, 'return'::text])),
  quantity numeric NOT NULL CHECK (quantity <> 0::numeric),
  unit_cost numeric NOT NULL DEFAULT 0 CHECK (unit_cost >= 0::numeric),
  total_cost numeric NOT NULL DEFAULT 0 CHECK (total_cost >= 0::numeric),
  reference_type text,
  reference_id uuid,
  performed_by uuid,
  note text,
  transaction_at timestamp with time zone NOT NULL DEFAULT now(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT inventory_transactions_pkey PRIMARY KEY (id),
  CONSTRAINT inventory_transactions_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id),
  CONSTRAINT inventory_transactions_item_id_fkey FOREIGN KEY (item_id) REFERENCES public.inventory_items(id)
);
CREATE TABLE public.pending_receipts (
  id uuid NOT NULL DEFAULT gen_uuid(),
  tenant_id uuid NOT NULL,
  purchase_request_id uuid,
  supplier_id uuid,
  expected_at timestamp with time zone,
  received_at timestamp with time zone,
  received_by uuid,
  items_json jsonb NOT NULL DEFAULT '[]'::jsonb,
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'partial'::text, 'received'::text, 'cancelled'::text])),
  note text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT pending_receipts_pkey PRIMARY KEY (id),
  CONSTRAINT pending_receipts_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id),
  CONSTRAINT pending_receipts_purchase_request_id_fkey FOREIGN KEY (purchase_request_id) REFERENCES public.purchase_requests(id),
  CONSTRAINT pending_receipts_supplier_id_fkey FOREIGN KEY (supplier_id) REFERENCES public.suppliers(id)
);
CREATE TABLE public.pending_dispatches (
  id uuid NOT NULL DEFAULT gen_uuid(),
  tenant_id uuid NOT NULL,
  destination text NOT NULL,
  items_json jsonb NOT NULL DEFAULT '[]'::jsonb,
  scheduled_at timestamp with time zone NOT NULL,
  dispatched_at timestamp with time zone,
  dispatched_by uuid,
  delivery_id uuid,
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'dispatched'::text, 'delivered'::text, 'cancelled'::text])),
  note text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT pending_dispatches_pkey PRIMARY KEY (id),
  CONSTRAINT pending_dispatches_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id),
  CONSTRAINT pending_dispatches_delivery_id_fkey FOREIGN KEY (delivery_id) REFERENCES public.deliveries(id)
);
CREATE TABLE public.workflows (
  id uuid NOT NULL DEFAULT gen_uuid(),
  tenant_id uuid NOT NULL,
  code text NOT NULL,
  name text NOT NULL,
  description text,
  dag_definition jsonb NOT NULL,
  status text NOT NULL DEFAULT 'draft'::text CHECK (status = ANY (ARRAY['draft'::text, 'published'::text, 'disabled'::text])),
  max_daily_executions integer NOT NULL DEFAULT 100 CHECK (max_daily_executions >= 0),
  trigger_type text,
  created_by uuid,
  last_executed_at timestamp with time zone,
  total_executions integer NOT NULL DEFAULT 0 CHECK (total_executions >= 0),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT workflows_pkey PRIMARY KEY (id),
  CONSTRAINT workflows_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id)
);
CREATE TABLE public.workflow_runs (
  id uuid NOT NULL DEFAULT gen_uuid(),
  tenant_id uuid NOT NULL,
  workflow_id uuid NOT NULL,
  trigger_type text NOT NULL CHECK (trigger_type = ANY (ARRAY['payment_overdue'::text, 'student_enrolled'::text, 'payment_recorded'::text, 'schedule'::text, 'absence_limit'::text, 'manual_run'::text, 'debt_over_threshold'::text])),
  triggered_at timestamp with time zone NOT NULL DEFAULT now(),
  started_at timestamp with time zone,
  completed_at timestamp with time zone,
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'running'::text, 'succeeded'::text, 'failed'::text, 'timeout'::text, 'cancelled'::text])),
  actor_id uuid,
  error_message text,
  duration_ms integer CHECK (duration_ms IS NULL OR duration_ms >= 0),
  node_results jsonb NOT NULL DEFAULT '[]'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT workflow_runs_pkey PRIMARY KEY (id),
  CONSTRAINT workflow_runs_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id),
  CONSTRAINT workflow_runs_workflow_id_fkey FOREIGN KEY (workflow_id) REFERENCES public.workflows(id)
);
CREATE TABLE public.workflow_audit_links (
  workflow_run_id uuid NOT NULL,
  audit_log_id uuid NOT NULL,
  tenant_id uuid NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT workflow_audit_links_pkey PRIMARY KEY (workflow_run_id, audit_log_id),
  CONSTRAINT workflow_audit_links_workflow_run_id_fkey FOREIGN KEY (workflow_run_id) REFERENCES public.workflow_runs(id),
  CONSTRAINT workflow_audit_links_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id),
  CONSTRAINT workflow_audit_links_audit_log_fk FOREIGN KEY (audit_log_id) REFERENCES public.audit_logs(id)
);
CREATE TABLE public.ai_provider_configs (
  id uuid NOT NULL DEFAULT gen_uuid(),
  tenant_id uuid NOT NULL,
  provider text NOT NULL CHECK (provider = ANY (ARRAY['groq'::text, 'openrouter'::text])),
  api_key_encrypted text NOT NULL,
  default_model text NOT NULL,
  fallback_model text,
  is_active boolean NOT NULL DEFAULT true,
  rate_limit_per_minute integer NOT NULL DEFAULT 60 CHECK (rate_limit_per_minute >= 0),
  last_used_at timestamp with time zone,
  created_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT ai_provider_configs_pkey PRIMARY KEY (id),
  CONSTRAINT ai_provider_configs_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id)
);
CREATE TABLE public.ai_request_logs (
  id uuid NOT NULL DEFAULT gen_uuid(),
  tenant_id uuid NOT NULL,
  user_id uuid NOT NULL,
  feature text NOT NULL CHECK (feature = ANY (ARRAY['narrative'::text, 'drafting'::text, 'anomaly'::text])),
  provider text NOT NULL,
  model text NOT NULL,
  prompt_token_count integer NOT NULL DEFAULT 0 CHECK (prompt_token_count >= 0),
  completion_token_count integer NOT NULL DEFAULT 0 CHECK (completion_token_count >= 0),
  latency_ms integer NOT NULL DEFAULT 0 CHECK (latency_ms >= 0),
  success boolean NOT NULL,
  error_message text,
  requested_at timestamp with time zone NOT NULL DEFAULT now(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT ai_request_logs_pkey PRIMARY KEY (id),
  CONSTRAINT ai_request_logs_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id)
);
CREATE TABLE public.calendar_events (
  id uuid NOT NULL DEFAULT gen_uuid(),
  tenant_id uuid NOT NULL,
  kind text NOT NULL CHECK (kind = ANY (ARRAY['payment_received'::text, 'audit_log'::text, 'expense_event'::text, 'follow_up_call'::text, 'reminder'::text, 'meeting'::text, 'custom'::text])),
  title text NOT NULL,
  description text,
  start_at timestamp with time zone NOT NULL,
  end_at timestamp with time zone,
  all_day boolean NOT NULL DEFAULT false,
  location text,
  attendee_count integer NOT NULL DEFAULT 0 CHECK (attendee_count >= 0),
  target_entity_type text,
  target_entity_id uuid,
  target_name text,
  target_phone text,
  created_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  is_deleted boolean NOT NULL DEFAULT false,
  CONSTRAINT calendar_events_pkey PRIMARY KEY (id),
  CONSTRAINT calendar_events_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id)
);
CREATE TABLE public.notifications (
  id uuid NOT NULL DEFAULT gen_uuid(),
  tenant_id uuid NOT NULL,
  kind text NOT NULL CHECK (kind = ANY (ARRAY['alert'::text, 'info'::text, 'warning'::text, 'success'::text, 'error'::text, 'system'::text])),
  title text NOT NULL,
  body text,
  priority text NOT NULL DEFAULT 'medium'::text CHECK (priority = ANY (ARRAY['low'::text, 'medium'::text, 'high'::text, 'urgent'::text])),
  source text NOT NULL DEFAULT 'system'::text CHECK (source = ANY (ARRAY['system'::text, 'manual'::text, 'workflow'::text, 'schedule'::text, 'audit'::text])),
  source_label text,
  target_user_id uuid,
  target_role text,
  is_read boolean NOT NULL DEFAULT false,
  read_at timestamp with time zone,
  dismissed_at timestamp with time zone,
  triggered_at timestamp with time zone NOT NULL DEFAULT now(),
  expires_at timestamp with time zone,
  link_entity_type text,
  link_entity_id uuid,
  created_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT notifications_pkey PRIMARY KEY (id),
  CONSTRAINT notifications_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id)
);
CREATE TABLE public.backup_archives (
  id uuid NOT NULL DEFAULT gen_uuid(),
  tenant_id uuid NOT NULL,
  archive_id_text text NOT NULL UNIQUE,
  file_name text NOT NULL,
  size_bytes bigint NOT NULL CHECK (size_bytes >= 0),
  checksum_sha256 text NOT NULL,
  vault_location text NOT NULL CHECK (vault_location = ANY (ARRAY['indexeddb'::text, 'local_drive'::text, 'offsite_vault'::text])),
  status text NOT NULL DEFAULT 'encrypted'::text CHECK (status = ANY (ARRAY['encrypted'::text, 'restored'::text, 'corrupted'::text, 'purged'::text])),
  retention_expires_at timestamp with time zone,
  created_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  restored_at timestamp with time zone,
  restored_by uuid,
  purge_at timestamp with time zone,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  CONSTRAINT backup_archives_pkey PRIMARY KEY (id),
  CONSTRAINT backup_archives_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id)
);
CREATE TABLE public.audit_logs (
  id uuid NOT NULL DEFAULT gen_uuid(),
  tenant_id uuid NOT NULL,
  action text NOT NULL,
  entity_type text NOT NULL,
  entity_id uuid,
  actor_id uuid,
  actor_name text,
  actor_role text,
  session_id uuid,
  before_json jsonb,
  after_json jsonb,
  note text,
  ip_address inet,
  user_agent text,
  request_id text,
  supersedes_id uuid,
  occurred_at timestamp with time zone NOT NULL DEFAULT now(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  diff jsonb,
  CONSTRAINT audit_logs_pkey PRIMARY KEY (id),
  CONSTRAINT audit_logs_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id),
  CONSTRAINT audit_logs_supersedes_id_fkey FOREIGN KEY (supersedes_id) REFERENCES public.audit_logs(id)
);
CREATE TABLE public.system_settings (
  id uuid NOT NULL DEFAULT gen_uuid(),
  tenant_id uuid NOT NULL,
  category text NOT NULL CHECK (category = ANY (ARRAY['connection'::text, 'ai'::text, 'email'::text, 'push'::text, 'storage'::text, 'backup'::text, 'system'::text, 'feature_flags'::text])),
  key text NOT NULL,
  label_fr text NOT NULL,
  label_ar text,
  label_en text,
  description_fr text,
  value_type text NOT NULL CHECK (value_type = ANY (ARRAY['string'::text, 'number'::text, 'boolean'::text, 'json'::text, 'secret'::text])),
  value jsonb,
  value_encrypted text,
  is_sensitive boolean NOT NULL DEFAULT false,
  is_editable boolean NOT NULL DEFAULT true,
  is_required boolean NOT NULL DEFAULT false,
  sort_order integer NOT NULL DEFAULT 100,
  validation_pattern text,
  validation_min numeric,
  validation_max numeric,
  options jsonb,
  updated_by uuid,
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT system_settings_pkey PRIMARY KEY (id),
  CONSTRAINT system_settings_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id)
);
CREATE TABLE public.sync_queue (
  id text NOT NULL,
  tenant_id uuid NOT NULL,
  entity text NOT NULL,
  operation text NOT NULL CHECK (operation = ANY (ARRAY['insert'::text, 'update'::text, 'delete'::text])),
  actor_id text,
  payload jsonb NOT NULL,
  source_file text,
  import_run_id text,
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'synced'::text, 'failed'::text, 'skipped_mock'::text])),
  attempts integer NOT NULL DEFAULT 0,
  last_error text,
  queued_at timestamp with time zone NOT NULL DEFAULT now(),
  last_attempt_at timestamp with time zone,
  pushed_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT sync_queue_pkey PRIMARY KEY (id),
  CONSTRAINT sync_queue_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id)
);
CREATE TABLE public.device_tokens (
  id uuid NOT NULL DEFAULT gen_uuid(),
  tenant_id uuid NOT NULL,
  user_id uuid NOT NULL,
  token text NOT NULL,
  platform text NOT NULL CHECK (platform = ANY (ARRAY['android'::text, 'ios'::text, 'web'::text])),
  app_version text,
  is_active boolean NOT NULL DEFAULT true,
  last_seen_at timestamp with time zone NOT NULL DEFAULT now(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT device_tokens_pkey PRIMARY KEY (id),
  CONSTRAINT device_tokens_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id)
);
CREATE TABLE public.homework (
  id uuid NOT NULL DEFAULT gen_uuid(),
  tenant_id uuid NOT NULL,
  class_id uuid NOT NULL,
  subject_id uuid NOT NULL,
  subject_name text NOT NULL,
  teacher_id uuid NOT NULL,
  teacher_name text NOT NULL,
  title text NOT NULL,
  description text NOT NULL,
  due_date date NOT NULL,
  attachments jsonb NOT NULL DEFAULT '[]'::jsonb,
  academic_year text NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  pushed_at timestamp with time zone,
  acknowledged_count integer NOT NULL DEFAULT 0,
  CONSTRAINT homework_pkey PRIMARY KEY (id),
  CONSTRAINT homework_class_id_fkey FOREIGN KEY (class_id) REFERENCES public.classes(id),
  CONSTRAINT homework_subject_id_fkey FOREIGN KEY (subject_id) REFERENCES public.subjects(id)
);
CREATE TABLE public.student_academic_histories (
  id uuid NOT NULL DEFAULT gen_uuid(),
  tenant_id uuid NOT NULL,
  student_id uuid NOT NULL,
  academic_year text NOT NULL,
  cycle text NOT NULL CHECK (cycle = ANY (ARRAY['prescolaire'::text, 'primaire'::text, 'cem'::text, 'lycee'::text])),
  grade_code text NOT NULL,
  grade_year integer NOT NULL,
  class_id uuid,
  class_name text,
  gpa numeric NOT NULL CHECK (gpa >= 0::numeric AND gpa <= 20::numeric),
  rank integer,
  decision text NOT NULL CHECK (decision = ANY (ARRAY['promoted'::text, 'repeated'::text, 'graduated'::text, 'transferred'::text])),
  narrative text,
  recorded_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT student_academic_histories_pkey PRIMARY KEY (id),
  CONSTRAINT student_academic_histories_class_id_fkey FOREIGN KEY (class_id) REFERENCES public.classes(id)
);