package com.example.domain.repository

import com.example.core.Result
import com.example.domain.model.DebtSummary
import com.example.domain.model.Installment
import com.example.domain.model.Payment
import kotlinx.coroutines.flow.Flow

/** Debt repository contract — aggregated parent-debt views. */
interface DebtRepository {
    fun observeSummary(): Flow<List<DebtSummary>>
    fun observeParentProfile(parentId: String): Flow<ParentFinancialProfile?>
    suspend fun sendReminder(parentId: String, actorId: String, actorName: String): Result<Unit>
}

/**
 * Aggregated parent financial profile — totals + installments + recent payments.
 *
 * TIER 2 R17 — added `adjustments` field. Mirrors the desktop's
 * `ParentFinancialProfile.adjustments: readonly AccountAdjustment[]`
 * (`src/domain/model/payment.ts:275`). Without this field, Android could
 * never display discretionary adjustment history (hardship waivers,
 * late penalties, parent_credits). The desktop's `UnifiedDebtMeter`
 * surfaces these in the UI; the Android UI now has the data available.
 */
data class ParentFinancialProfile(
    val parentId: String, val parentName: String,
    val totalDue: Long, val totalPaid: Long, val totalOutstanding: Long, val overdueAmount: Long,
    val installments: List<Installment>, val recentPayments: List<Payment>,
    val adjustments: List<AccountAdjustment> = emptyList(),
)

/**
 * TIER 2 R17 — discretionary adjustment entry on a parent account.
 *
 * Mirrors the desktop's `AccountAdjustment` interface
 * (`src/domain/model/payment.ts:256-264`). The `amount` is signed:
 *   - negative = credit (school owes parent — e.g., hardship waiver)
 *   - positive = debit (parent owes more — e.g., late penalty)
 *
 * The `approvedBy` + `approvedAt` pair records the audit trail of who
 * authorized the adjustment and when. `receiptRef` is the optional
 * receipt number tied to the adjustment (when generated by a payment
 * workflow).
 */
data class AccountAdjustment(
    val id: String,
    val parentId: String,
    val amount: Long,           // signed — +debit / -credit (centimes)
    val reason: String,
    val approvedBy: String,
    val approvedAt: String,
    val receiptRef: String?,
)
